def load_bh_file(fn):
    """
    Load the BH corners file generated by scrape_bh.txt
    :param fn: path to bh.txt file.
    :type fn: str
    :return: list(str)
    """
    with open(fn, "r") as bh:
        return [i.replace("\n", "") for i in bh.readlines()]
